kafka:
  bootstrap_servers: localhost:9092
  topic: trips

mongo:
  mongo_uri: "mongodb+srv://projectrealtimer:{senha_mongodb}@cluster0.eev9reb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  mongo_db: "tripsdb"
  mongo_collection: "trips"